### ISSUE TITLE
U+2588 Problem with NanumBarunCatsi

### ISSUE THREAD

**Issue by XCninety** [Nu-SCPTheme/Black-Highlighter#103]
Good day, Woed.

I've found that in Korean settings the Full Block character (U+2588, █) are showing gaps between themselves.

Here is the current version of SCP-2316 in Korean Branch, which uses BHL:

![image](https://user-images.githubusercontent.com/56790522/129445086-d17a205a-d9a7-435d-bdc7-d3b99cd6b211.png)

Here is the intened display:

![image](https://user-images.githubusercontent.com/56790522/129445112-627f4530-46f7-492c-8646-46902b50cc19.png)

In the original Nanum Barun Gothic font, while writing U+2588 successively the gap always exists. What I have done while making "NanumBarunCatsi" was getting rid of the U+2588 solely to make reference of other fonts. However, the gaps which has to be defininitely disappeared (and it was, for the time the Korean branch made use of this font of our own) are showing up again. Are there any ways to apply other fonts only for U+2588 to remove the gaps?

By the way, this problem does not show up on mobile settings. (Android Pi)

**Comment by XCninety** [comment]
Sorry for inconvenience, but I think I have found the solution for this. Can you edit the root.int.css file
`	--body-font: Inter, NanumBarunCatsi, "Apple SD Gothic Neo", "NanumBarunGothic",
		"맑은 고딕", "Malgun Gothic", "굴림", "Gulim", "돋움", "Dotum",
		"Helvetica Neue", "Helvetica", Arial, sans-serif;`
into
`	--body-font: Inter, NanumBarunCatsi, "Apple SD Gothic Neo", 
		"맑은 고딕", "Malgun Gothic", "굴림", "Gulim", "돋움", "Dotum",
		"Helvetica Neue", "Helvetica", Arial, sans-serif;`
? I think that the reason this issue occurs comes from the fact that "NanumBarunGothic" overrides NanumBarunCatsi. Two fonts are essentially same, so we might not need "NanumBarunGothic".

**Comment by Woedenaz** [comment]
Got it! I'll make that change now.
