### ISSUE TITLE
The problem didn't solved

### ISSUE THREAD

**Issue by bitterlord** [Nu-SCPTheme/Black-Highlighter#104]
**Describe the issue:**  
As you might remember, I had a problem with 'image-block'. After that you said you solved and closed the tread. But it isn't changed at all. 

![image](https://user-images.githubusercontent.com/88598402/129482851-4f61bff6-b054-48bf-8353-f4c8ed1331cd.png)
(I made the square in right)

**Link to the page(s) having this issue:**  
http://selimtan.wikidot.com/testullah2 (Altough same thing happens in both my sites and every pages.)

**Device information:** (fill in as appropriate)  
 - Device: Lenovo Ideapad 3 and Xiaomi Redmi 8
 - OS: Windows 10 and Android 10
 - Browser: Opera GX and Chrome (Phone and PC)
 - Version: Latest

**Additional context:**  
As a reminder, you said it doesnt happens in '.scp-image-block' but only 'image-block'

Thanks for help in advance.

**Comment by Woedenaz** [comment]
This definitely appears fixed. I've checked on multiple devices. I think you may need to refresh your cache as your device might still have the old css file.

![image](https://user-images.githubusercontent.com/46789324/129483992-8ed5c184-f028-4886-9236-9030a3efd079.png)

**Comment by bitterlord** [comment]
Yes, it is fixed now, thanks Woed!
