### ISSUE TITLE
Interwiki-Module not displayed on mobile, also would be too wide if it was displayed

### ISSUE THREAD

**Issue by Grombald** [Nu-SCPTheme/Black-Highlighter#105]
**Describe the issue:**  
A bug with the priorities of CSS selectors makes the Interwiki-module not be visible on mobile.

If it would be visible, it would be too wide

**Screenshot showcasing the issue:** 
Interwiki-module not visible:
![](https://cdn.discordapp.com/attachments/374970501497487362/876517557857841272/unknown.png)

Interwiki-module visible by disabling problematic property, but too wide:
![](https://cdn.discordapp.com/attachments/374970501497487362/876517265267367996/unknown.png)

**Link to the page(s) having this issue:**  
http://scp-wiki.wikidot.com/scp-5004

**Device information:** (fill in as appropriate)  
 - Browser: Firefox 91.0

**Additional context:**  
The selector 
```css
#side-bar div.scpnet-interwiki-wrapper:not(:lang(cn)), #side-bar div.scpnet-interwiki-wrapper:not(:lang(cn)) *
```
seems to have a higher priority than 
```css
@media only screen and (max-width: 56.25rem) {
    #side-bar div.scpnet-interwiki-wrapper, #side-bar div.scpnet-interwiki-wrapper *
```

Also `max-width: var(--sidebar-width-on-mobile);` is too wide for the interwiki module.

**Comment by Woedenaz** [comment]
Thank you, Grom! I pushed a fix to add the `:not(:lang(cn))` selector to the mobile version. Also added a `margin-left: 0` which will help a bit with the positioning. I'll have to keep experimenting to see if I can fix the width issue.

**Comment by Woedenaz** [comment]
I'm going to close this because it's at least visible now. I'll work on getting it to fit in the set width at a later date.
