### ISSUE TITLE
About The Strokes On Headers

### ISSUE THREAD

**Issue by bitterlord** [Nu-SCPTheme/Black-Highlighter#112]
How can I make them not to exist? Because in some themes, they do not look good.

**Comment by Denevola** [comment]
Try inserting the following code somewhere on your page.
```
[[module CSS]]
:root {
    --diagonal-stripes: none;
}
[[/module]]
```

**Comment by bitterlord** [comment]
Well, nothing have changed unfortunately.

**Comment by Woedenaz** [comment]
You'll need to specify what you mean by "Strokes on Header", Bitterlord. I am unsure what you mean exactly.

**Comment by bitterlord** [comment]
Sorry for not being able to answer for such a long time.

![image](https://user-images.githubusercontent.com/88598402/179252080-4e9d3e31-4294-45e0-a7a6-9e924435edc4.png)

As you can see here, all of the BHL themes has these strokes around header texts. I want to make them dissapear in my own themes, how can I do it?
