### ISSUE TITLE
Remove all fixes for Russia SCP Branch

### ISSUE THREAD

**Issue by MrNereof** [Nu-SCPTheme/Black-Highlighter#120]
Recently,  Russia SCP Branch Sigma9 theme has been adapted from English site. Now we have many problems with BHL due to fixes for our branch. Can you remove all fixes?

**Comment by Woedenaz** [comment]
Ah, yes, I can!

Apologies for the delay on this, I was taking an extended break. I'll fix this up asap.

**Comment by jewalky** [comment]
Note: except code that implements display: grid on menu items please :)

**Comment by Woedenaz** [comment]
Just pushed this! Should be live momentarily. Thank you for the heads up!
