### ISSUE TITLE
Printer-Friendly Mode Glitch

### ISSUE THREAD

**Issue by wolf20482** [Nu-SCPTheme/Black-Highlighter#126]
**Describe the issue:**  
Sidebar on pages with collapsible BHL sidebar will glitch in printer-friendly mode

**Screenshot showcasing the issue:**  

![bhlbug](https://user-images.githubusercontent.com/40973492/153535945-576350ed-c1d6-442e-a924-872101b0d892.png)

**Link to the page(s) having this issue:**  
[Collapsible Sidebar component page (printer-friendly version).](https://scp-wiki.wikidot.com/printer--friendly//component:collapsible-sidebar)

**Device information:** (fill in as appropriate)  
 - Device: Dell Inspiron Laptop
 - OS: Windows 10
 - Browser: Chrome
 - Version: Chrome 97.0.4692.99 (64 bit) (cohort: Stable)

**Additional context:**  
None

**Comment by SYwaves** [comment]
`
    body.print-body {
        --sidebar-width-on-desktop: 0;
    }
    body.print-body #main-content::before,
    body.print-body #main-content::after {
        display: none;
    }
`
Putting this in the component page should be enough to solve it.

**Comment by Woedenaz** [comment]
Thanks much, Estrella! I added that to the component page. :]
