### ISSUE TITLE
Safari Mobile Break

### ISSUE THREAD

**Issue by stormbreath** [Nu-SCPTheme/Black-Highlighter#137]
While on mobile, the width of the `.page-watch-options`, `#page-info` and `.page-tags` breaks to something around 180vw (rough estimate), causing them to float off the side of the screen.

<details>
<summary>Screenshots</summary>

![1](https://user-images.githubusercontent.com/8848022/176748754-ed935e12-e11f-4839-95a5-c4b9e95f7d8f.jpg)

![2](https://user-images.githubusercontent.com/8848022/176748653-52efd35f-1b2c-427c-9368-40e0a937a9ee.jpg)

![3](https://user-images.githubusercontent.com/8848022/176748666-9cc88cad-57a5-4b29-8471-ad4f417d1d57.jpg)
</details>

This bug is present on all pages that use BHL.

**Device information:**
 - Device: iPhone SE
 - OS: iOS 15.5
 - Browser: "Chrome" (which is actually Safari on the backend)
 - Version: 102.0.5005.87

**Comment by SYwaves** [comment]
> #action-area-top {
>    grid-area: action-area-top;
>    width: var(--body-width-on-desktop);
>}

The width property is causing the issue. It can be resolved by removing the property or setting it to 100%.

**Comment by Woedenaz** [comment]
Just pushed the fix for this. Thanks for catching that, Estrella!
