### ISSUE TITLE
Broken media icons for -PT

### ISSUE THREAD

**Issue by L2-01** [Nu-SCPTheme/Black-Highlighter#139]
**Describe the issue:**  
-PT has replaced side-links with media, therefore causing issues with media icons.

**Screenshot showcasing the issue:**  (https://media.discordapp.net/attachments/421363805344235531/991913542750064710/unknown.png)

**Link to the page(s) having this issue:**  
http://scp-pt-br.wikidot.com/theme:dustjacket# example of page suffering from this issue.

**Device information:** (fill in as appropriate)  
 - Device: Computer.
 - OS: Windows 10
 - Browser: Chrome
 - Version: Chrome 103

**Additional context:**  
Not much to say, I guess.

**Comment by Woedenaz** [comment]
This should be working again! Thanks for the heads up and apologies for not fixing it sooner.
