### ISSUE TITLE
How to Change Logo Location

### ISSUE THREAD

**Issue by bitterlord** [Nu-SCPTheme/Black-Highlighter#143]
In some of the themes like **PENUMBRA** 
![image](https://user-images.githubusercontent.com/88598402/179353368-6fb74bcb-a556-4a72-a792-4df6bb7d8ac7.png)
or the theme I am using for my site 
![image](https://user-images.githubusercontent.com/88598402/179353407-ff46eae7-37a5-4dfc-9159-ee90cfa4e3e9.png)
has this particular problem with logos; logo is below the nav:top. PENUMBRA can be explained with the size of logo. But how can I change the height of my logo? Thanks in advance.

**Comment by Woedenaz** [comment]
I'm not entirely sure what you are asking here. Do you want to make the logo larger?

**Comment by Woedenaz** [comment]
@bitterlord I'm closing this for now. If you can come back and give me more details I'll reopen it.
