### ISSUE TITLE
Need to make it clearer that the side bar scrolls separately (or pick another behavior)

### ISSUE THREAD

**Issue by Woedenaz** [Nu-SCPTheme/Black-Highlighter#15]
Currently, it is unclear to some users that the sidebar scrolls independently of the main content. We need to come up with a solution as to how to make this clearer and/or come up with a different way of implementing the side-bar.

Looking at Firefox, it seems the scrollbar on the side bar is totally missing, which should not be the case. For now, I'll go in to the stable version and make sure that gets fixed.

Another option I've seen is to add an arrow to the bottom of the scroll window that disappears once you get to the top. This can be achieved using background-attachment: local; See here: http://lea.verou.me/2012/04/background-attachment-local/

**Comment by rossjrw** [comment]
Having the scrollbar appear only on mouseover should fix this

**Comment by rossjrw** [comment]
I've set the scrollbar to appear only on mouseover, but that pushes the sidebar contents to the left on mouseover as well.

I'd set a margin-right on the non-hovered sidebar that's as wide as the scrollbar, but I'm concerned that this might not be valid for browsers that don't let you change the width of the scrollbar in the first place.

**Comment by Woedenaz** [comment]
I personally quite like the current behavior and I think the collapsible sidebar menu we have mocked up will help out here as well.

**Comment by Woedenaz** [comment]
We can't really implement the collapsible sidebar on the main wiki so I think what we have now with the shadows on the top and bottom as well as the scrollbar that appears on hover is about as good as it's going to get (better than YouTube, even :p)
