### ISSUE TITLE
Topbar Problems of Updated Theme

### ISSUE THREAD

**Issue by bitterlord** [Nu-SCPTheme/Black-Highlighter#151]
There are some bugs that I have faced with both my site and SCP Wiki (Sandbox of BHL)

![image](https://user-images.githubusercontent.com/88598402/193872305-93016e76-776b-4ee0-83b3-6da8755ab0dd.png)
![image](https://user-images.githubusercontent.com/88598402/193872373-df3ffdec-d073-45d1-9e45-a8ee0712b636.png)

**Link to the page(s) having this issue:**  
[It is not possible to debug the styling without being able to see the page in question. Please add links of where this issue is occurring.
http://scptestwiki.wikidot.com
http://odrin.wikidot.com/

**Device information:** (fill in as appropriate)  
 - Device: Lenovo Ideapad 3
 - OS: Win11
 - Browser: Chrome
 - Version: Latest

**Comment by Woedenaz** [comment]
Looking at your site, I do not see any issues. It's been quite a few months since you reported this, is it still occurring?

**Comment by Woedenaz** [comment]
@bitterlord I'm closing this for now. If you can come back and give me more details I'll reopen it.
