### ISSUE TITLE
style.css stylesheet?

### ISSUE THREAD

**Issue by coleweev** [Nu-SCPTheme/Black-Highlighter#156]
Is there the potentiality of having a style.css stylesheet for this theme uploaded into the master folder?

**Comment by emmiegit** [comment]
I don't understand this question. Are you saying the final, compiled CSS file should be version controlled? Storing generated binaries in VC is not good practice.

If you want to see generated CSS files, look at [the `gh-pages` branch](https://github.com/Nu-SCPTheme/Black-Highlighter/tree/gh-pages/css).

**Comment by coleweev** [comment]
Maybe I got ahead of myself - is it remotely possible to adapt this theme
to Wordpress? When attempting to bring the css over to Wordpress it
pestered me for a style sheet which I was unable to locate. (I’m not the
most technically proficient in this arena)

**Comment by emmiegit** [comment]
Black Highlighter is structured specifically to match Wikidot's (rather unusual) DOM structure. WordPress has an entirely different structure, so making "Black Highlighter for WordPress" would involve you completely rewriting the theme. Which given the theme's license, you are permitted to do if you so wish.

**Comment by emmiegit** [comment]
Interesting, there are different close reasons now.
