### ISSUE TITLE
Firefox and Safari: All icons implemented as backgrounds lost size and repeat settings

### ISSUE THREAD

**Issue by jewalky** [Nu-SCPTheme/Black-Highlighter#158]
Reproduces both in EN and RU (where we found it)

https://scp-wiki.wikidot.com/theme:black-highlighter-theme
https://scpfoundation.net/theme:black-highlighter-theme

Screenshot:

![image](https://user-images.githubusercontent.com/5638098/203825880-b84d4048-3f8b-4fd9-8690-48241b491fa3.png)

In addition, in RU:

![image](https://user-images.githubusercontent.com/5638098/203826041-594ef2c6-bfba-4532-9a69-e4a76a40cc8e.png)

Firefox 107.0 on Windows 11.
Safari 16.1 (18614.2.9.1.12) via Browserstack.
Chrome is correct.

This only happened today.

**Comment by emmiegit** [comment]
This is the CSS minifier issue occurring again. I've reverted it for now.
