### ISSUE TITLE
Strange sidebar scroll behavior

### ISSUE THREAD

**Issue by Woedenaz** [Nu-SCPTheme/Black-Highlighter#16]
As per user feedback:

> if you scroll all the way to the bottom on the sidebar, it will scroll the article, but if you begin to scroll up from the bottom on the sidebar, it will scroll the article, IT WILL NOT SCROLL THE SIDEBAR until you hit the top of the article, and THEN it will scroll the sidebar up

I have not been able to repeat this bug myself but we should try and see what is causing it.

**Comment by pxdnbluesoul** [comment]
I can reliably have it not begin to scroll the article up or down until the sidebar scrolls all the way to one end, and then I move the mouse and continue to scroll in that direction. Latest Chrome and Firefox.

**Comment by rossjrw** [comment]
Should now be fixed with the addition of `overscoll-behavior: none`

**Comment by rossjrw** [comment]
I'm actually finding this to be less intuitive than before. Any thoughts?

**Comment by Woedenaz** [comment]
I don't like either way, truthfully. I think this method might make the most "logical" sense, though. Hard to say.

**Comment by Woedenaz** [comment]
I'm calling this one closed. I think we've gotten this about the best we can with the way we have it now. I also added shadows that appear on the top and bottom when there is space to scroll (indicating that it can be scrolled.)
