### ISSUE TITLE
Border bug around scp-image-block & caption

### ISSUE THREAD

**Issue by JakdragonX** [Nu-SCPTheme/Black-Highlighter#179]
**Describe the issue:**  
BHL now surrounds all images (and image captions) in a 1px border.

**Screenshot showcasing the issue:**  
[Screenshot_20230506_224619_Chrome](https://user-images.githubusercontent.com/90160558/236693090-36aeae05-a309-4c18-810d-a659c42e4c80.jpg)

**Link to the page(s) having this issue:**  
https://scp-wiki.wikidot.com/theme:new-age
https://scp-wiki.wikidot.com/theme:penumbra-bhl
(Et. al)

**Device information:** (fill in as appropriate)  
 - Device: Samsung Fold 4
 - OS: Android 13
 - Browser: Chrome
 - Version: Chrome 112.0.5615.135

**Additional context:**  
I haven't verified all of the themes but it's occurring on atleast the specified two I listed above. May need to investigate further.

**Comment by Woedenaz** [comment]
Just pushed a hotfix that will remove this!

**Comment by JakdragonX** [comment]
Hi Woed,

Super sorry to disturb but it looks like there might still be either a top or bottom border between the image and the caption. Is this intentional?

[Screenshot_20230508_094508_Chrome](https://user-images.githubusercontent.com/90160558/236840682-978f877a-ac1a-43de-8691-163a746595e5.jpg)

**Comment by Woedenaz** [comment]
Ah, got it. Yeah, that was intentional but I put together a better way of doing it that should cause less issues. Thank you for pointing that out!
