### ISSUE TITLE
Page Editing "Show Changes" Code Difference Highlighting not working

### ISSUE THREAD

**Issue by ChaosMageX** [Nu-SCPTheme/Black-Highlighter#184]
**Describe the issue:**  
BHL's page code difference highlighting isn't working when Editing a page.

**Screenshot showcasing the issue:**  
BHL's page code difference highlighting isn't working when I click the **Show Changes** button when **Editing** a page:
![2023-05-09_18h56_00](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8120512/f1fcd920-159e-41d9-a86e-15e7dddfe1b5)
It does work when I use the **Compare versions** button in a page's **History**, though:
![2023-05-09_18h58_03](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8120512/685da56a-62ea-4520-9c9b-572fbd33e5d9)

**Link to the page(s) having this issue:**  
Any BHL styled page, but the screenshots are from my test page:
http://scptestwiki.wikidot.com/cmxtest1

**Device information:** (fill in as appropriate)  
 - Device: Custom Built PC (Do I need to provide full specs?)
 - OS: Windows 10 (64-bit)
 - Browser: Chrome
 - Version: 112.0.5615.138 (Official Build) (64-bit)

**Additional context:**  
This should be able to be tested on literally any Wikidot page that uses the BHL Theme.

**Comment by Woedenaz** [comment]
This should be fixed

**Comment by ChaosMageX** [comment]
No, unfortunately it doesn't seem to be fixed yet.

This is what I saw in the **Show Changes** view during the last edit of my hub page:
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8120512/f1688781-7c59-42a6-bb21-6bee9e8c154e)

This is what I see in the **Compare versions** view in my hub page's **History** after applying that edit:
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8120512/68553d39-344a-485a-8122-5357b068a04e)

**Comment by Woedenaz** [comment]
This actually for sure works now
