### ISSUE TITLE
<hr> Element Styling/Behavior?

### ISSUE THREAD

**Issue by ChaosMageX** [Nu-SCPTheme/Black-Highlighter#185]
**Describe the issue:**  
Some of the recent changes to BHL seem to have broken your **"Fancy Stars"** in your **UIU BHL Theme**, and it might break custom **hr** styling in other derivative themes too.

**Screenshot showcasing the issue:**  
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8120512/109971b5-1218-4e25-b1c5-3412763c1739)

**Link to the page(s) having this issue:**  
https://scp-wiki.wikidot.com/theme:uiu-bhl-theme

**Device information:** (fill in as appropriate)  
 - Device: Custom Built PC (Do I need to provide full specs?)
 - OS: Windows 10 (64-bit)
 - Browser: Chrome
 - Version: 112.0.5615.138 (Official Build) (64-bit)

**Additional Context:**
Maybe this was intentional and all derivative themes now have to adapt to it? It appears that you already closed a separate issue regarding **hr** elements, and this may be the result of what you did to fix that issue. Still, the **UIU BHL Theme** is one of your own derivative themes, so I'm opening this issue regardless so that you can fix it in either the BHL Theme's core code or in that derivative theme's code.

**Comment by Woedenaz** [comment]
This was just a specificity issue. BHL uses `#main-content hr` as the selector now since some branches use `hr` in the sidebar and some other random places.
