### ISSUE TITLE
ListPages Page Links Styling

### ISSUE THREAD

**Issue by ChaosMageX** [Nu-SCPTheme/Black-Highlighter#187]
**Describe the issue:**  
I think the styling is completely broken on the page links at the top/bottom of any ListPages module with multiple pages of results.

**Screenshot showcasing the issue:**
At the top of the Recent Changes list:
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8120512/255214dd-d048-47b6-9656-1f753253f767)
At the bottom of a ListPages module on my hub page:
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8120512/3bc2a92f-0265-47d4-ab86-0674c0929c42)

**Link to the page(s) having this issue:**  
http://scptestwiki.wikidot.com/system:recent-changes

http://scptestwiki.wikidot.com/chaos-hub

**Device information:** (fill in as appropriate)  
 - Device: Custom Built PC (Do I need to provide full specs?)
 - OS: Windows 10 (64-bit)
 - Browser: Chrome
 - Version: 112.0.5615.138 (Official Build) (64-bit)

**Additional context:**  
This issue can be tested with any ListPages module that results in multiple pages, on any page that uses the BHL theme.

**Comment by Woedenaz** [comment]
This should be fixed.

**Comment by ChaosMageX** [comment]
It's mostly fixed, but some of the page link numbers don't seem to be properly center-aligned on the ListPages module on my hub page:
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8120512/21667f12-5ec7-4b25-81ba-fda2ac9c72ca)
