### ISSUE TITLE
CSS localization no longer work on SCP-ZH's Wiki

### ISSUE THREAD

**Issue by Viken-K** [Nu-SCPTheme/Black-Highlighter#189]
**Describe the issue:**  
I discovered that the file under `src/css/parts/int` has been changed to `:lang(zh-tr)`, but the originally matched one is `:lang(zh)`.

**Screenshot showcasing the issue:**  
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/60818826/bce71e68-df9d-4c2b-baa6-fe6800ada647)
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/60818826/36ffd78c-6d50-445f-a1f1-bb5cefaecbd3)
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/60818826/84d0789f-7e76-4bb3-a241-29c709fe2892)

**Link to the page(s) having this issue:**  
Our main site is currently using code from JP as a replacement, so we will switch to our official sandbox (with the same language settings) for the demonstration.
[BHL without :root](http://scp-sandbox2-zh.wikidot.com/draft:3981670-j-lhwo9k57)
[BHL with :root:lang(zh)](http://scp-sandbox2-zh.wikidot.com/draft:3981670-18-95a6)
[BHL with :root:lang(zh-tr)](http://scp-sandbox2-zh.wikidot.com/draft:3981670-12-c262)

**Device information:** (fill in as appropriate)  
 - Device: ASUS X540NV
 - OS: Windows 10 22H2
 - Browser: Chrome
 - Version: 113.0.5672.127 (64bit)

**Comment by Woedenaz** [comment]
Ah, okay, I was mistaken with the language code. I just pushed a fix for this so it should be corrected in just a moment.
