### ISSUE TITLE
Text in topbar doesn't show up correctly (only Korean)

### ISSUE THREAD

**Issue by XCninety** [Nu-SCPTheme/Black-Highlighter#190]
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/56790522/470353a5-ffe2-4164-882b-6036e1ea9bdd)

Text in topbar are placed above the intended position, while upper and lower fractions of texts are cut.

This issue occurs only on the Korean settings as far as I know.

I've found that if I disable this code
```
/* TOP MENU */
#top-bar ul li a {
     max-height: 1px;
}
```
then it shows up properly.

Example link: http://scpko.wikidot.com/scp-4781

Similar issue (closed): https://github.com/Nu-SCPTheme/Black-Highlighter/issues/151

**Comment by Woedenaz** [comment]
Strange! I'll give this a look. Thank you for the report!

**Comment by Woedenaz** [comment]
This should be fixed momentarily! I also fixed the topbar arrow used on the common theme that wasn't centered correctly.
