### ISSUE TITLE
odialogs go offscreen on mobile

### ISSUE THREAD

**Issue by scutoid-bkr** [Nu-SCPTheme/Black-Highlighter#193]
**Describe the issue:**  
after updating the backrooms wiki's theme to use the newest version of bhl (before it had an archived version from 2020) i've gotten a lot of reports from users that popup dialogs like the user info page or the "you have a draft saved" dialog don't show properly on mobile devices. i don't have access to a mobile device right now, so i can't get screenshots or test things myself, but i've asked users of backrooms wiki to get me some:

**Screenshot showcasing the issue:**  
the issue on backrooms-wiki (liminal theme):
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/135032340/b7e3e14b-e099-4390-9032-4588184976f5)

the issue on scptestwiki (base bhl theme):
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/135032340/a6ea4f21-504c-4909-b0a2-6b6f4185c770)

**Link to the page(s) having this issue:**  
To see it for yourself, click a [[user]] link on mobile on any page.

**Device information:** (fill in as appropriate)  
all I was told by the person who got those screenshots was that it was on a redmi phone, which runs on android. but i'm quite sure this would happen no matter what

**Comment by scutoid-bkr** [comment]
some additional information:
on desktop, when i resize the window to trigger the mobile view, the dialog _does_ go the right size.
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/135032340/96534284-5f94-4098-863a-5c37f90fcbea)

i do know it's not just this person's redmi phone, because multiple users have complained of this issue. if i can get my hands on a phone sometime soon, i'll test this out on it.

**Comment by hoah2333** [comment]
Same things happen on the top bar on mobile, and I predict that it's because the `translate` property (which is only full support on Chrome 104 and above) is not working properly on some devices, especially on those outdated browsers. And hope it can be fixed by adding some compatible patch. For example: 
```css
@supports not (translate: -50%) {
    .foo {
        transform: translate(-50%);
    }
}
```

**Comment by Woedenaz** [comment]
Ah, good to know! I can definitely patch that in there. There's a few other places I use the alternative scale/rotate/translate instead of transform that I might need to add this as well.

**Comment by Woedenaz** [comment]
This should, hopefully, be fixed with this commit: https://github.com/Nu-SCPTheme/Black-Highlighter/commit/730f8d60b244c8dd657b7a920a42ad59f5f816d8

I tested it on browserstack and it seems to solve the issue. Let me know if you encounter anything else!
