### ISSUE TITLE
[Mobile Issue] scp-image-caption div is much wider than its content

### ISSUE THREAD

**Issue by lt-flops** [Nu-SCPTheme/Black-Highlighter#194]
### Describe the issue:

In mobile environments, `scp-image-caption` is often much wider than the text it contains. This occurs regardless of the length of the text inside the caption, and involves `scp-image-block.block-right` specifically. As a result, the caption stretches beyond the screen extents, creating a horizontal scrollbar.

### Screenshot showcasing the issue:

**SCP-1730 — Firefox Nightly 115 vs. Google Chrome 114**
![1730ffn](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/101367591/31aa36b7-fe5e-46a4-887c-8e38ce8aff85)
![1730gc](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/101367591/9b58dce5-54f0-4570-ba4b-be62b7c5e6c4)

**SCP-5001 — Firefox Nightly 115 vs. Google Chrome 114**
![5001ffn](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/101367591/c68ebcf8-6276-4016-a217-1e5825d113ee)
![5001gc](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/101367591/29363d0c-e7a7-4867-8ca2-f777b88ba5c0)

**SCP-5241 — Firefox Nightly 115 vs. Google Chrome 114**
![5241ffn](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/101367591/442a0e0e-4a06-45f8-b063-fcf9a576dd48)
![5241gc](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/101367591/8875c236-5391-442f-a5ca-41499c2a47ed)

### Link to the pages having this issue:

https://scp-wiki.wikidot.com/scp-1730
https://scp-wiki.wikidot.com/scp-5001
https://scp-wiki.wikidot.com/scp-5421

Occurs on many BHL pages that use a right-aligned standard image block.

### Device information:
 - **Device:** Google Pixel 3
 - **OS:** Android 12
 - **Browser:** Firefox Nightly 115 + Google Chrome 114

**Comment by Woedenaz** [comment]
How strange! I'll look into that and fix it right now.

**Comment by Woedenaz** [comment]
This should be fixed!
