### ISSUE TITLE
Compressed image caption text

### ISSUE THREAD

**Issue by emmiegit** [Nu-SCPTheme/Black-Highlighter#195]
**Describe the issue:**  
Image blocks seem to shrink the width of the text in the captions in an unusual way.

**Screenshot showcasing the issue:**  
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8848022/a882e97b-abd3-4435-835d-d62ead422056)
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8848022/47f18058-9b53-4db1-aa49-f6921df8c645)
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8848022/9ee857f4-cba2-4345-b920-714bbf4868aa)

**Link to the page(s) having this issue:**  
* https://scp-wiki.wikidot.com/scp-6852
* https://scp-wiki.wikidot.com/scp-6364
* https://scp-wiki.wikidot.com/scp-7152

**Device information:** Firefox Developer Edition (first two screenshots), Chrome (all three)

Filed on behalf of another user.

**Comment by SYwaves** [comment]
This is actually a problem inherent with the image block component itself when using percentage width instead of unit. While it can be patched in BHL, I believe it more prudent to do this on the component level.

That said, my prior attempt to do it while largely fine, had conflict with wide image sizer.

**Comment by emmiegit** [comment]
The wide image sizer feels to me like kind of a stopgap solution in the BHL ecosystem, if it's causing an issue is there something we could do to refactor it?

**Comment by SYwaves** [comment]
My prelim inspection suggest that WIS relies on the inline width property to function properly, so adding it back in the CSS module should be functional - but it also has a lot of weird design decision belying, so I'd rather a top down refactoring, yes.

(Also, I missed this before, but the image block should also have `align-items: stretch;` in conjunction with the above to fully fix the issue.)

**Comment by Woedenaz** [comment]
I would definitely be happy to see a refactoring of the image-block, for sure! If this can be improved on a component level instead of a theme level, we definitely should. That way it would be a universal improvement on all themes.

**Comment by emmiegit** [comment]
Since we have some basic agreement, what do ae need to action this? We should probably also bring this to Tech chat so people can see and weigh in.

**Comment by Woedenaz** [comment]
With the redundant widths removed from the image block on the scp-wiki, this issue appears to be fixed! Closing this since it doesn't seem like any other changes are needed.
