### ISSUE TITLE
Page source view style conflict?

### ISSUE THREAD

**Issue by SYwaves** [Nu-SCPTheme/Black-Highlighter#198]
**Describe the issue:**  
`page-source` in page sourc view has no border and top padding.

**Screenshot showcasing the issue:**  
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/93550009/31c035e9-0668-4f40-ae45-3794b32a09a0)

**Additional context:**  
Possible style conflict due to this selector:
```
#action-area
	> div:not([style*="center"]):first-of-type {
		padding-top: 0;
		border: none;
	}
```

**Comment by Woedenaz** [comment]
This should be fixed momentarily.
