### ISSUE TITLE
Remove header background image from /printer--friendly/ view

### ISSUE THREAD

**Issue by TSATPWTCOTTTADC** [Nu-SCPTheme/Black-Highlighter#20]
`print-options` is hard to read and not as printer friendly as it could be due to the dark background image.

Replicated on Windows 7 in Firefox 64 and Chrome 71. Not replicable in Internet Explorer 11 as IE 11 doesn't display the header background in either this view or regular article view.

![firefox_1drwuwcrku](https://user-images.githubusercontent.com/37148714/51874218-1936cb80-232e-11e9-81cf-86a2f2cf85c6.png)

**Comment by rossjrw** [comment]
Print Preview on Chrome eliminates the background and a lot of other special formatting, as seen below:

![print preview](https://i.imgur.com/Bgx80DI.png)

"Printed" PDF on Firefox looks the same.

Unless the printer--friendly mode is important for something, or if someone's printing directly from printer--friendly (but why?), then this is very low priority

**Comment by Woedenaz** [comment]
This is essentially a duplicate of #28.
