### ISSUE TITLE
Collapsible Text Wrapping

### ISSUE THREAD

**Issue by montagueETC** [Nu-SCPTheme/Black-Highlighter#204]
**Describe the issue:**  
Collapsible text won't wrap in mobile view, it just keeps going off the side.

**Screenshot showcasing the issue:**  
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/137567842/76ce413b-aaaf-4e1f-9516-eadf31e200ef)

**Link to the page(s) having this issue:**  
http://scpdsandbox.wikidot.com/collapsible-problem

**Device information:**
Tested on both Galaxy S21+ (/w Firefox) & desktop Firefox using Responsive Design Mode

**Additional context:**  
N/A

**Comment by Woedenaz** [comment]
I just pushed a fix for this, though it's not perfect. Wikidot enforces the use of `&nbsp;` or non-breaking spaces between words on Collapsible Block Links. No clue why but this causes the browser to consider the entire link a single "word." So if I add line breaking to the link, it will break at any point with no hyphenation or consideration of word length. That results in line breaks like this:
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/46789324/652cfd8e-a660-4a6c-af73-a008c481da73)

There's no workaround for this so it's something we have to live with until we decide to move away from Wikidot (or Wikidot decides to update their antiquated code... but we all know which is more likely here.)
