### ISSUE TITLE
Table Vertical Centering

### ISSUE THREAD

**Issue by montagueETC** [Nu-SCPTheme/Black-Highlighter#205]
**Describe the issue:**  
Text won't automatically vertically center in tables like it used to.

**Screenshot showcasing the issue:**  
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/137567842/d18954ca-a286-414e-b8d4-bf8636f0dd02)

**Link to the page(s) having this issue:**  
https://scp-wiki.wikidot.com/scp-7701

**Device information:**
Windows 10 w/ Firefox

**Additional context:**  
N/A

**Comment by Woedenaz** [comment]
Thanks for reporting these! 

I just pushed a fix for this as well. Will make sure every table element is automatically vertically aligned to the middle.
