### ISSUE TITLE
Table Headers

### ISSUE THREAD

**Issue by montagueETC** [Nu-SCPTheme/Black-Highlighter#206]
**Describe the issue:**  
Table headers aren't centered.

**Screenshot showcasing the issue:**  
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/137567842/c8aa3cfc-5092-4235-8de2-470fc93a77ac)

**Link to the page(s) having this issue:**  
https://scp-wiki.wikidot.com/scp-7701

**Device information:** (fill in as appropriate)  
Galaxy S21+ (/w Firefox) & Windows 10 /w Firefox

**Additional context:**  
Sorry to keep harping on about text spacing in tables.

**Comment by Woedenaz** [comment]
This was fixed by Estrella and pushed here: https://github.com/Nu-SCPTheme/Black-Highlighter/pull/219
