### ISSUE TITLE
Subscript bug

### ISSUE THREAD

**Issue by RedEyeMikey** [Nu-SCPTheme/Black-Highlighter#225]
**Describe the issue:**  Like the title, there is a bug about subscript letters/number with BHL
**Screenshot showcasing the issue:**  
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/114435496/90a8a7d9-2c8f-4a28-b41b-dc2fb1c323cc)
**Link to the page(s) having this issue:**  
http://scp-vn.wikidot.com/scp-030-vn
**Device information:** 
 - Device: Laptop
 - OS: Windows 10
 - Browser: Chrome

**Comment by Woedenaz** [comment]
Just pushed a fix that should remedy this!
