### ISSUE TITLE
File module on mobile way too big

### ISSUE THREAD

**Issue by emmiegit** [Nu-SCPTheme/Black-Highlighter#243]
**Describe the issue:**  
Going to Files >> Info on mobile yields a popup that's way too huge and not possible to close because it takes up the whole screen. There is too much spacing between items in the info box.

**Screenshot showcasing the issue:**  
![Screenshot_20240123-111720](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8848022/4eae0ebb-7379-479d-92e1-443dcb0fdebb)
![Screenshot_20240123-111553](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/8848022/3cf7d565-7428-43ef-8a82-bfadc44ea13c)

**Link to the page(s) having this issue:**  
https://scp-wiki.wikidot.com/scp-6415
https://scp-wiki.wikidot.com/scp-7957
But any BHL page with files should work to reproduce

**Device information:** (fill in as appropriate)  
 - Device: Pixel 2
 - OS: Android 11
 - Browser: Firefox Beta
 - Version: 122.09b

However multiple people on various mobile devices have reported similar issues.

**Additional context:**  
Reported by naepic

**Comment by Woedenaz** [comment]
Just pushed a fix for this! Here: https://github.com/Nu-SCPTheme/Black-Highlighter/commit/ae154e651aaded2ca71ce57aa7ad5f1d8c5ef8cb

**Comment by Woedenaz** [comment]
@emmiegit Just checked and this appears to have been fixed now! Feel free to double check, though.

**Comment by emmiegit** [comment]
Seems good to me.
