### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Sekai-s** [Nu-SCPTheme/Black-Highlighter#39]
As the side bar menu structures are different in the sandbox and other language branches, I think it will be better use this selector:
#side-bar .side-block[style="background-color: #f0fff6;"]{background-color: ...

instead of nth-child(#)

The other thing, the two local variables in :root :
--swatch-headerh1-color
--swatch-headerh2-color

I think it's used to change the color of header title. But they are isolated and do not change anything.

**Comment by Woedenaz** [comment]
ah, correct you are on the variables. I'll get that sorted out.

As for the attribute selectors, that is a good idea, I'll see about implementing that. Thank you!

**Comment by Woedenaz** [comment]
These changes have been implemented! :D
