### ISSUE TITLE
Small icon issues for pro users

### ISSUE THREAD

**Issue by rossjrw** [Nu-SCPTheme/Black-Highlighter#40]
Base BHL:

![Screenshot 2019-06-02 at 22 01 30](https://user-images.githubusercontent.com/29130152/58767381-1d941f00-8582-11e9-863b-da885d0db398.png)

without `width: min-content` on `span>a[href*="user:info"]`:

![Screenshot 2019-06-02 at 22 01 39](https://user-images.githubusercontent.com/29130152/58767389-33a1df80-8582-11e9-8cc7-ae430700e80a.png)

This of course creates a huge gap for non-pro users

Doesn't look like there's a way to detect pro vs non-pro users, or karma, given that all Wikidot does is [provide an overlay image](http://www.wikidot.com/userkarma.php?u=2893766) for each user - so no way to recreate pro/karma ourselves.

**Comment by Woedenaz** [comment]
I went ahead and removed the min-content. Having a bit of space to the left of the name isn't that big of a deal. Thanks for catching that!
