### ISSUE TITLE
Investigate concerns about font legibility

### ISSUE THREAD

**Issue by rossjrw** [Nu-SCPTheme/Black-Highlighter#41]
http://strangehorizons.com/fiction/the-skinwalkers-ball/
http://www.nightmare-magazine.com/fiction/hungry-daughters-of-starving-mothers/
http://clarkesworldmagazine.com/valente_03_19_reprint/
https://www.newyorker.com/magazine/2019/02/18/the-confession
http://www.lightspeedmagazine.com/fiction/ambitious-boys-like-you/
https://dailysciencefiction.com/hither-and-yon/magic-realism/karen-heuler/my-life-as-a-rattler
https://www.apex-magazine.com/the-prison-house-of-language/
https://www.tor.com/2016/09/28/the-city-born-great/

**Comment by rossjrw** [comment]
http://scptestwiki.wikidot.com/fonts

**Comment by Woedenaz** [comment]
I think this has been more or less taken care of at this point. Closing this.
