### ISSUE TITLE
Slashes followed by greater-than turn into arrows

### ISSUE THREAD

**Issue by ammongit** [Nu-SCPTheme/Black-Highlighter#46]
See http://scptestwiki.wikidot.com/arrow-tests vs http://scptestwiki.wikidot.com/sigma:arrow-tests.

![image](https://user-images.githubusercontent.com/8848022/75719222-580e2200-5ca2-11ea-9832-14c15bb56055.png)
![image](https://user-images.githubusercontent.com/8848022/75719228-5b091280-5ca2-11ea-922b-52128d09ff46.png)

This is a nuisance since doing `[[/>]]` turns into `[[↗]]` which makes copy-able templates difficult.

**Comment by rossjrw** [comment]
https://docs.microsoft.com/en-gb/typography/opentype/spec/features_ae#tag-calt

It's the `calt` setting on font-feature-settings:

https://github.com/Nu-SCPTheme/Black-Highlighter/blob/5309581742bbc06699496bc11b61c18d17bd44c4/src/css/structure.css#L25

https://github.com/Nu-SCPTheme/Black-Highlighter/blob/635f39f9b557643ce0f2a170192a2a7e9ae7b37f/src/css/int/chn/black-highlighter_ch.css#L212

**Comment by Woedenaz** [comment]
Just pushed a fix for this. This shouldn't happen in code/pre/tt blocks anymore. If someone uses the monofont OUTSIDE of that, like manually via CSS, it will still occur but I believe that is acceptable.
