### ISSUE TITLE
No margin between blockquotes on mobile

### ISSUE THREAD

**Issue by rossjrw** [Nu-SCPTheme/Black-Highlighter#53]
<img src="https://media.discordapp.net/attachments/669352764111061002/719358136724750357/image0.png?width=919&height=671" height="300">

**Comment by ammongit** [comment]
What media queries are we using that's different from sigma? I don't think it has this problem on mobile.

**Comment by Woedenaz** [comment]
Just fixed this. There was a setting making 0 margin on mobile for blockquotes. I made it so there is a 0.75em top and bottom margin only instead. Should be implemented momentarily.
