### ISSUE TITLE
Meta titles do not match the styling of regular page titles

### ISSUE THREAD

**Issue by ammongit** [Nu-SCPTheme/Black-Highlighter#60]
Following the implementation of [Adult Content Warninings](http://05command.wikidot.com/forum/t-13896072/adult-content-warnings), a `.meta-title` style was added to Sigma-9 to mimic the styling of the title, but allowed to be implemented in the body of the page, allowing for HTML to be "above" it (due to our lack of DOM control). See https://github.com/scpwiki/sigma9/pull/38.

However BHL has not been updated to match. See how a sigma page compares to a BHL page:

![image](https://user-images.githubusercontent.com/8848022/102706178-8ffc4b00-425d-11eb-8dad-6823ec42fe41.png)
----
![image](https://user-images.githubusercontent.com/8848022/102706181-938fd200-425d-11eb-8e06-962bb10e5a08.png)

Any styles that apply to `#page-title` should be modified to apply to `.meta-title` as well, as if they were the same element.

**Comment by Woedenaz** [comment]
Added the .meta-title class! This should be available to use now.
