### ISSUE TITLE
Sorry if I'm wrong, but I'm having a little problem with the layout.

### ISSUE THREAD

**Issue by Enderman-desu5214** [Nu-SCPTheme/Black-Highlighter#71]
Hey! My name is Enderman_desu, and I'm active in the SCP-JP Wiki.
It's just a minor layout issue, but in every BlackHighLighter Theme, the footnote size is insanely huge!
In case you're wondering, the one below is for "[The Coalition Theme](http://www.scpwiki.com/theme:the-coalition-theme)", and it's as big as a normal body font.
![The Coalition Theme - SCP Foundation - Google Chrome 2021_03_24 8_26_04](https://user-images.githubusercontent.com/71477115/112231875-e6bd5a80-8c7a-11eb-828a-00b0238778ba.png)
At least I didn't think this layout was intentional, so I'm reporting it this way. I'm sorry if it was an intentional alteration:)

At least this one is.
[[module CSS]]
a.footnoteref {
    font-size: 1px;
}
[[/module]]
It's a trivial problem that can be solved with the above code, 
but I hope they can fix it for the sake of the great articles already posted ;)
I'm sorry to be selfish, but I think the BlackHighlighter Theme is a great design and I respect the people who created it. I think the BlackHighlighter Theme is a great design, and I respect the people who created it, so thank you for your time.

**Comment by Woedenaz** [comment]
Hey hey! Yeah, I made this change a few days ago. I unfortunately assumed `font-variant: super;` worked on Chrome/Safari but it seems it does not.

I just pushed a new change that will add `font-variant-numeric: diagonal-fractions;` to chrome and webkit-based browsers that should remedy this issue. Apologies for my mistake!
