### ISSUE TITLE
Issues with Tables

### ISSUE THREAD

**Issue by dysadron** [Nu-SCPTheme/Black-Highlighter#91]
Hey Woed! Thank you for the latest BHL update, having a few issues with a table I have on my author page though:

http://scp-wiki.wikidot.com/dysadron

The table now extends outside of the "normal" page width, and some of the images appear smaller despite being the same size. I didn't have either of these issues prior to the update so I _think_ it's not just me being useless with tech. Thanks, Dys

**Comment by Woedenaz** [comment]
Hmm. Looks like it's something to do with the table and max-width. I'll see what I can do. Sorry for the inconvenience!

**Comment by Woedenaz** [comment]
This is fixed! Thank you for the report, Dysadron!
