### ISSUE TITLE
Button width on non-English languages

### ISSUE THREAD

**Issue by bitterlord** [Nu-SCPTheme/Black-Highlighter#93]
The new look of BHL is neat, but there is a problem about it. With some of languages, bottom doesn't works good as English.7

**Example:**

![](https://media.discordapp.net/attachments/764475432241856532/873655813418409994/unknown.png)

As you can see, some letters are out of the boxes and thus, invisible.

I hope this gets fixed soon.

**Comment by Woedenaz** [comment]
Yup! I had someone else mention this as well. I'll need to increase the min-width on the page-options buttons for those languages. Apologies!

**Comment by bitterlord** [comment]
Yes! Thank you, also there is one more problem... In a theme I created on my test page, all uppercase stuff looks like this;
[https://media.discordapp.net/attachments/764475432241856532/873681577488568350/unknown.png](url)
[https://cdn.discordapp.com/attachments/764475432241856532/873682416835895306/unknown.png](url)
Some of the letters are uppercase, some are big as uppercase but lowercase. But I do not see this on SCP Wiki. Do you have a knowledge about it?

**Comment by Woedenaz** [comment]
@bitterlord I opened this as a new issue. Please see here: https://github.com/Nu-SCPTheme/Black-Highlighter/issues/94

**Comment by Woedenaz** [comment]
This issue has been fixed, though I might explore a better option later. But, for now, the buttons will be large enough for the languages that need it.
