### ISSUE TITLE
Lower and uppercase letters mixing

### ISSUE THREAD

**Issue by Woedenaz** [Nu-SCPTheme/Black-Highlighter#94]
Yes! Thank you, also there is one more problem... In a theme I created on my test page, all uppercase stuff looks like this;
[https://media.discordapp.net/attachments/764475432241856532/873681577488568350/unknown.png](url)
[https://cdn.discordapp.com/attachments/764475432241856532/873682416835895306/unknown.png](url)
Some of the letters are uppercase, some are big as uppercase but lowercase. But I do not see this on SCP Wiki. Do you have a knowledge about it?

_Originally posted by @bitterlord in https://github.com/Nu-SCPTheme/Black-Highlighter/issues/93#issuecomment-894709954_

**Comment by Woedenaz** [comment]
Bitterlord, can you link the page you're seeing this on?

**Comment by bitterlord** [comment]
http://selimtan.wikidot.com/start Here.

**Comment by Woedenaz** [comment]
oh I love this theme!
Okay, give me just a sec. I think I might know what it is.

**Comment by bitterlord** [comment]
I'm so glad that you liked the theme, thanks.

**Comment by Woedenaz** [comment]
Yup! The font you're using for this theme (Raleway) has stylistic sets built in and BHL enables those by default. Just add this to your theme code:
```css
:root {
	--ss01: 0;
	--ss02: 0;
	--ss03: 0;
}
```

**Comment by bitterlord** [comment]
It works! Thank you so much for helping me Woed, also for your compliment.

**Comment by Woedenaz** [comment]
Of course :]
Happy to help :D
