### ISSUE TITLE
A Question About New Theme

### ISSUE THREAD

**Issue by bitterlord** [Nu-SCPTheme/Black-Highlighter#95]
Hello, Woed. Are you planning on making those logos changable. That would be nice. Or, if it has a way to do it now, can you teach us how? Thanks!

![image](https://user-images.githubusercontent.com/88598402/128615175-02ddfc8a-d02d-429d-94d0-33ce5214dfbf.png)

**Comment by Woedenaz** [comment]
These logos are all encoded SVGs in the CSS. You can find them all here:
https://github.com/Nu-SCPTheme/Black-Highlighter/blob/master/src/css/wikidot-structure.css#L545

I made them in Illustrator (though you can use any program that lets you save svg files) and then use [this page](https://yoksel.github.io/url-encoder/) to encode them. You just copy the `url("data:image/svg+xml-blahblahblah");` that it generates (ignore the background-image part) and replace the `--button-icon:` code.

**Comment by bitterlord** [comment]
Thanks, I will try this.
